name: foodie
description: Unified Marketplace App - Foodie (customer) and Cook Hub (seller) in one application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  fl_chart: ^0.65.0
  image_picker: ^1.0.0
  # firebase_messaging: ^14.6.0
  google_maps_flutter: ^2.5.0
  google_places_flutter: ^2.0.4
  geocoding: ^2.1.1
  geolocator: ^9.0.0
  url_launcher: ^6.2.0
  socket_io_client: ^2.0.1
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0
  image: ^4.1.3
  google_sign_in: ^6.2.0
  flutter_facebook_auth: ^6.0.0
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/categories/
    - assets/cooks/
    - assets/dishes/
    - assets/navigation/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
